#!/usr/bin/env bash
#
# Half-Life: Decay -- Linux support installer for Steam Deck / desktop Linux.
#
# Decay's PC port ships only decay.dll (Windows). Valve never built the mod for
# Linux, so on a Deck the menu loads but no map ever starts. This installs the
# missing native libraries and the one config line that points the engine at them.
#
# It does NOT install the Decay mod itself -- get that from ModDB first.

set -euo pipefail

say()  { printf '  %s\n' "$*"; }
die()  { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -f "$HERE/lib/decay.so" ]  || die "lib/decay.so missing -- run this from inside the unpacked folder"
[ -f "$HERE/lib/client.so" ] || die "lib/client.so missing -- run this from inside the unpacked folder"

echo
echo "Half-Life: Decay -- Linux support installer"
echo "==========================================="
echo

# ---- 1. locate Half-Life across every Steam library ------------------------
say "Looking for Half-Life..."
STEAM_ROOT=""
for c in "$HOME/.local/share/Steam" "$HOME/.steam/steam" "$HOME/.steam/root"; do
    [ -d "$c/steamapps" ] && { STEAM_ROOT="$c"; break; }
done
[ -n "$STEAM_ROOT" ] || die "no Steam installation found under \$HOME"
say "Steam root: $STEAM_ROOT"

LIBS=("$STEAM_ROOT/steamapps")
LF="$STEAM_ROOT/steamapps/libraryfolders.vdf"
if [ -f "$LF" ]; then
    while IFS= read -r p; do
        [ -d "$p/steamapps" ] && LIBS+=("$p/steamapps")
    done < <(grep -oP '(?<="path"\s{2})"[^"]*"' "$LF" 2>/dev/null | tr -d '"')
fi

H=""
for l in "${LIBS[@]}"; do
    if [ -f "$l/common/Half-Life/hl.sh" ]; then H="$l/common/Half-Life"; break; fi
done
[ -n "$H" ] || die "Half-Life not found. Install it from Steam first (it must be the Linux build)."
say "Half-Life:  $H"

# ---- 2. the Decay mod itself must already be there -------------------------
[ -d "$H/decay" ] || die "No 'decay' folder in $H
       Install the Decay PC port first, then re-run this.
       It goes in:  $H/decay"
[ -f "$H/decay/liblist.gam" ] || die "$H/decay exists but has no liblist.gam -- incomplete mod install"
say "Decay mod:  found"

# ---- 3. sanity-check we are targeting the right architecture ---------------
if grep -q 'GAMEEXE=hl_linux64' "$H/hl.sh" 2>/dev/null; then
    die "This install uses the 64-bit engine; these libraries are 32-bit."
fi
say "Engine:     32-bit (hl_linux) -- matches these libraries"

# ---- 4. install the libraries ---------------------------------------------
mkdir -p "$H/decay/dlls" "$H/decay/cl_dlls"
for pair in "decay.so:dlls" "client.so:cl_dlls"; do
    f="${pair%%:*}"; d="${pair##*:}"
    if [ -f "$H/decay/$d/$f" ]; then
        cp -a "$H/decay/$d/$f" "$H/decay/$d/$f.bak-$(date +%Y%m%d-%H%M%S)"
        say "backed up existing $d/$f"
    fi
    install -m644 "$HERE/lib/$f" "$H/decay/$d/$f"
    say "installed   decay/$d/$f"
done

# ---- 5. point liblist.gam at the Linux library (CRLF-safe, idempotent) -----
python3 - "$H/decay/liblist.gam" <<'PY'
import shutil, sys
from datetime import datetime
p = sys.argv[1]
raw = open(p, "rb").read()
eol = b"\r\n" if raw.count(b"\r\n") else b"\n"
if b"gamedll_linux" in raw:
    print("  liblist.gam already has gamedll_linux -- unchanged")
    raise SystemExit
out, done = [], False
for ln in raw.split(eol):
    out.append(ln)
    if not done and ln.strip().lower().startswith(b"gamedll "):
        out.append(b'gamedll_linux "dlls/decay.so"'); done = True
if not done:
    raise SystemExit("ERROR: no gamedll line in liblist.gam to anchor on")
shutil.copy2(p, p + ".bak-" + datetime.now().strftime("%Y%m%d-%H%M%S"))
open(p, "wb").write(eol.join(out))
print("  liblist.gam  + gamedll_linux \"dlls/decay.so\"  (%s endings preserved)"
      % ("CRLF" if eol == b"\r\n" else "LF"))
PY

# ---- 6. launcher ------------------------------------------------------------
# GoldSrc will not start outside the Steam Runtime: no distro ships 32-bit SDL2
# in a way the game finds, so bare ./hl.sh dies with "Could not load hw.so".
RT="$STEAM_ROOT/ubuntu12_32/steam-runtime/run.sh"
LAUNCHER="$HOME/decay.sh"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# Launch Half-Life: Decay. Generated by install.sh on $(date +%Y-%m-%d).
#
# 1. GoldSrc will not start outside the Steam Runtime (no system-wide 32-bit SDL2).
# 2. As a non-Steam shortcut the game inherits the SHORTCUT's app id; Half-Life is
#    app 70, so SteamAPI_Init rejects it and quits in ~1s with "[S_API FAIL] ...
#    Failed to initalize authentication interface". SteamAppId=70 fixes that.
# 3. Do NOT also set SteamGameId. gamescope tracks the launched game by that id and
#    will not display a window that disagrees, logging "xwm: appid clash" and leaving
#    Game Mode spinning on "launching executable" forever.
set -u
H="$H"
RT="$RT"
[ -x "\$H/hl.sh" ]               || { echo "Half-Life not found at \$H" >&2; exit 1; }
[ -x "\$RT" ]                    || { echo "Steam Runtime not found at \$RT" >&2; exit 1; }
[ -f "\$H/decay/dlls/decay.so" ] || { echo "decay.so missing - no map will load" >&2; exit 1; }
export SteamAppId=70
cd "\$H" || exit 1
exec "\$RT" ./hl.sh -game decay "\$@"
LAUNCH
chmod +x "$LAUNCHER"
say "launcher    $LAUNCHER"
[ -x "$RT" ] || say "WARNING: Steam Runtime not at $RT -- start Steam once, then re-run"

# ---- 7. verify --------------------------------------------------------------
echo
say "Verifying..."
MISS=$(LD_LIBRARY_PATH="$H" ldd "$H/decay/dlls/decay.so" 2>&1 | grep -ci "not found" || true)
if [ "$MISS" != "0" ]; then
    LD_LIBRARY_PATH="$H" ldd "$H/decay/dlls/decay.so" 2>&1 | grep -i "not found" | sed 's/^/    /'
    die "$MISS unresolved dependencies -- your glibc may be older than these builds need.
       Rebuild from https://github.com/FWGS/hlsdk-portable (branch decay-pc)."
fi
say "decay.so:   all dependencies resolve"
say "client.so:  $(LD_LIBRARY_PATH="$H" ldd "$H/decay/cl_dlls/client.so" 2>&1 | grep -ci 'not found' || true) unresolved"

cat <<DONE

Done.

  Test it:   $LAUNCHER

  Add to Steam (Desktop Mode):
    Steam -> Games -> Add a Non-Steam Game -> Browse -> $LAUNCHER
    Rename it to "Half-Life: Decay", then right-click -> Properties for artwork.

  Playing: Decay has no New Game -- it is co-op only. Use "Play Decay" and start
  a server on dy_accident1 with 3 player slots. You control one of two scientists
  and swap with G, so bind G to a back paddle. Later maps unlock as you finish
  them, and there are no mid-mission saves. Both are original PS2 behaviour.
DONE
